export const raceConfig = {
    circuits: [
        {
            id: "miami",
            country: "North America, USA",
            name: "Miami International Autodrome",
            location: "Miami",
            flag: "🇺🇸",
            image: "./circuits/miami-circuit.png",
        },
        {
            id: "montreal",
            country: "North America, Canada",
            name: "Circuit Gilles Villeneuve (Montreal)",
            location: "Montreal",
            flag: "🇨🇦",
            image: "./circuits/montreal-circuit.png",
        },
        {
            id: "austin",
            country: "North America, USA",
            name: "Circuit of the Americas (Austin)",
            location: "Austin",
            flag: "🇺🇸",
            image: "./circuits/austin-circuit.png",
        },
        {
            id: "lasvegas",
            country: "North America, USA",
            name: "Las Vegas Strip Circuit",
            location: "Las Vegas",
            flag: "🇺🇸",
            image: "./circuits/las-vegas-circuit.png",
        },
        {
            id: "mexico",
            country: "South America, Mexico",
            name: "Autódromo Hermanos Rodríguez",
            location: "Mexico City",
            flag: "🇲🇽",
            image: "./circuits/mexico-circuit.png",
        },
    ],

    eras: [
        {
            id: "1950s",
            title: "Gentlemen Racers Era",
            years: "1950–1959",
            image: "./eras/1950.jpg",
            promptStyle: "vintage film grain, classic open-wheel cars",
        },
        {
            id: "1960s",
            title: "Space Age Speed",
            years: "1960–1969",
            image: "./eras/1960.jpg",
            promptStyle: "retro futurism, bold color tones",
        },
        {
            id: "1970s",
            title: " Raw Power Revolution",
            years: "1970–1979",
            image: "./eras/1970.jpg",
            promptStyle: "gritty, high-contrast, muscle cars with exaggerated features",
        },
        {
            id: "1980s",
            title: "Turbo & Neon Dreams",
            years: "1980–1989",
            image: "./eras/1980.jpg",
            promptStyle: "neon lighting, turbo era aesthetic",
        },
        {
            id: "1990s",
            title: "Golden Precision Era",
            years: "1990–1999",
            image: "./eras/1990.jpg",
            promptStyle: "realistic broadcast style, 90s race suit design",
        },
        {
            id: "2000s",
            title: "2000s Tech Boom",
            years: "2000–2009",
            image: "./eras/2000.jpg",
            promptStyle: "high-tech, modern F1 aesthetics",
        },
        {
            id: "2010s",
            title: "Hybrid Power Era",
            years: "2010–2019",
            image: "./eras/2010.jpg",
            promptStyle: "contemporary F1 style, realistic lighting",
        },
        {
            id: "2020s",
            title: "Sustainable Speed Era",
            years: "2020–2029",
            image: "./eras/2020.jpg",
            promptStyle: "ultra-realistic, modern F1 aesthetics",
        },
        {
            id: "2030s",
            title: "AI-Driven Racing Era",
            years: "2030–2039",
            image: "./eras/2030.jpg",
            promptStyle: "futuristic, AI-controlled cars, advanced tech",
        },
        {
            id: "2040s",
            title: "Futuristic Flight Era",
            years: "2040–2049",
            image: "./eras/2040.jpg",
            promptStyle: "flying cars, anti-gravity tech, sleek futuristic design",
        },
    ],
};
