export const raceConfig = {
    circuits: [
        {
            id: "albert-park",
            country: "Oceania, Australia",
            name: "Albert Park Circuit",
            location: "Melbourne",
            flagCode: "au",
            image: "./circuits/albert-park-circuit-australia.jpg",
        },
        {
            id: "yas-marina",
            country: "Middle East, UAE",
            name: "Yas Marina Circuit",
            location: "Abu Dhabi",
            flagCode: "ae",
            image: "./circuits/yas-marina-circuit-emirates.jpg",
        },
        {
            id: "lusail",
            country: "Middle East, Qatar",
            name: "Lusail International Circuit",
            location: "Lusail",
            flagCode: "qa",
            image: "./circuits/lusail-international-circuit-qatar.jpg",
        },
        {
            id: "marina-bay",
            country: "Asia, Singapore",
            name: "Marina Bay Street Circuit",
            location: "Singapore",
            flagCode: "sg",
            image: "./circuits/marina-bay-street-circuit-singapore.jpg",
        },
        {
            id: "baku",
            country: "Asia, Azerbaijan",
            name: "Baku City Circuit",
            location: "Baku",
            flagCode: "az",
            image: "./circuits/baku-city-circuit-azerbaijan.jpg",
        },
        {
            id: "jeddah",
            country: "Middle East, Saudi Arabia",
            name: "Jeddah Corniche Circuit",
            location: "Jeddah",
            flagCode: "sa",
            image: "./circuits/jeddah-corniche-circuit-saudi-arabia.jpg",
        },
        {
            id: "bahrain",
            country: "Middle East, Bahrain",
            name: "Bahrain International Circuit",
            location: "Sakhir",
            flagCode: "bh",
            image: "./circuits/bahrain-international-circuit_.jpg",
        },
        {
            id: "suzuka",
            country: "Asia, Japan",
            name: "Suzuka Circuit",
            location: "Suzuka",
            flagCode: "jp",
            image: "./circuits/suzuka-circuit-japan.jpg",
        },
        {
            id: "shanghai",
            country: "Asia, China",
            name: "Shanghai International Circuit",
            location: "Shanghai",
            flagCode: "cn",
            image: "./circuits/shanghai-international-circuit.jpg",
        },
        {
            id: "interlagos",
            country: "South America, Brazil",
            name: "Autódromo José Carlos Pace",
            location: "São Paulo",
            flagCode: "br",
            image: "./circuits/autodromo-jose-carlos-pace-brazil.jpg",
        },
        {
            id: "mexico-city",
            country: "North America, Mexico",
            name: "Autódromo Hermanos Rodríguez",
            location: "Mexico City",
            flagCode: "mx",
            image: "./circuits/autodromo-hermanos-rodriguez-mexico.jpg",
        },
        {
            id: "las-vegas",
            country: "North America, USA",
            name: "Las Vegas Strip Circuit",
            location: "Las Vegas",
            flagCode: "us",
            image: "./circuits/las-vegas-strip-circuit.jpg",
        },
        {
            id: "austin",
            country: "North America, USA",
            name: "Circuit of the Americas",
            location: "Austin",
            flagCode: "us",
            image: "./circuits/circuit-of-the-americas-austin.jpg",
        },
        {
            id: "montreal",
            country: "North America, Canada",
            name: "Circuit Gilles Villeneuve",
            location: "Montreal",
            flagCode: "ca",
            image: "./circuits/circuit-gilles-villeneuve-montreal.jpg",
        },
        {
            id: "miami",
            country: "North America, USA",
            name: "Miami International Autodrome",
            location: "Miami",
            flagCode: "us",
            image: "./circuits/miami-international-autodrome.jpg",
        },
        {
            id: "monza",
            country: "Europe, Italy",
            name: "Autodromo Nazionale Monza",
            location: "Monza",
            flagCode: "it",
            image: "./circuits/autodromo-nazionale-monza.jpg",
        },
        {
            id: "zandvoort",
            country: "Europe, Netherlands",
            name: "Circuit Zandvoort",
            location: "Zandvoort",
            flagCode: "nl",
            image: "./circuits/circuit-zandvoort-netherlands.jpg",
        },
        {
            id: "hungaroring",
            country: "Europe, Hungary",
            name: "Hungaroring",
            location: "Mogyoród",
            flagCode: "hu",
            image: "./circuits/hungaroring-hungary.jpg",
        },
        {
            id: "spa",
            country: "Europe, Belgium",
            name: "Circuit de Spa-Francorchamps",
            location: "Spa",
            flagCode: "be",
            image: "./circuits/circuit-spa-francorchamps-belgium.jpg",
        },
        {
            id: "red-bull-ring",
            country: "Europe, Austria",
            name: "Red Bull Ring",
            location: "Spielberg",
            flagCode: "at",
            image: "./circuits/red-bull-ring-austria.jpg",
        },
        {
            id: "madrid",
            country: "Europe, Spain",
            name: "Circuit Madrid",
            location: "Madrid",
            flagCode: "es",
            image: "./circuits/circuit-madrid.jpg",
        },
        {
            id: "barcelona",
            country: "Europe, Spain",
            name: "Circuit Barcelona",
            location: "Barcelona",
            flagCode: "es",
            image: "./circuits/circuit-barcelona.jpg",
        },
        {
            id: "silverstone",
            country: "Europe, United Kingdom",
            name: "Silverstone Circuit",
            location: "Silverstone",
            flagCode: "gb",
            image: "./circuits/silverstone-circuit-uk.jpg",
        },
        {
            id: "monaco",
            country: "Europe, Monaco",
            name: "Circuit Monaco",
            location: "Monaco",
            flagCode: "mc",
            image: "./circuits/circuit-monaco.jpg",
        },
    ],

    eras: [
        {
            id: "1950s",
            title: "Gentlemen Racers Era",
            years: "1950–1959",
            image: "./eras/1950.png",
            promptStyle: "vintage film grain, classic open-wheel cars",
        },
        {
            id: "1960s",
            title: "Space Age Speed",
            years: "1960–1969",
            image: "./eras/1960.png",
            promptStyle: "retro futurism, bold color tones",
        },
        {
            id: "1970s",
            title: " Raw Power Revolution",
            years: "1970–1979",
            image: "./eras/1970.png",
            promptStyle: "gritty, high-contrast, muscle cars with exaggerated features",
        },
        {
            id: "1980s",
            title: "Turbo & Neon Dreams",
            years: "1980–1989",
            image: "./eras/1980.png",
            promptStyle: "neon lighting, turbo era aesthetic",
        },
        {
            id: "1990s",
            title: "Golden Precision Era",
            years: "1990–1999",
            image: "./eras/1990.png",
            promptStyle: "realistic broadcast style, 90s race suit design",
        },
        {
            id: "2000s",
            title: "2000s Tech Boom",
            years: "2000–2009",
            image: "./eras/2000.png",
            promptStyle: "high-tech, modern F1 aesthetics",
        },
        {
            id: "2010s",
            title: "Hybrid Power Era",
            years: "2010–2019",
            image: "./eras/2010.png",
            promptStyle: "contemporary F1 style, realistic lighting",
        },
        {
            id: "2020s",
            title: "Sustainable Speed Era",
            years: "2020–2029",
            image: "./eras/2020.png",
            promptStyle: "ultra-realistic, modern F1 aesthetics",
        },
        {
            id: "2030s",
            title: "AI-Driven Racing Era",
            years: "2030–2039",
            image: "./eras/2030.png",
            promptStyle: "futuristic, AI-controlled cars, advanced tech",
        },
        {
            id: "2040s",
            title: "Futuristic Flight Era",
            years: "2040–2049",
            image: "./eras/2040.png",
            promptStyle: "flying cars, anti-gravity tech, sleek futuristic design",
        },
    ],
};
