name: "Build and Copy Apps"

permissions:
  contents: write

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'

jobs:
  filter-paths:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      landingpage: ${{ steps.filter.outputs.landingpage }}
      photo-booth: ${{ steps.filter.outputs.photo-booth }}
      portfolio-agent: ${{ steps.filter.outputs.portfolio-agent }}
      videowall: ${{ steps.filter.outputs.videowall }}
      changed_apps: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          #define the filters for each app here. The key has to match the src-folder.
          filters: |
            landingpage:
              - '.github/workflows/build.yml'
              - 'src/common/**'
              - 'src/landingpage/**'
            photo-booth:
              - '.github/workflows/build.yml'
              - 'src/common/**'
              - 'src/photo-booth/**'
            portfolio-agent:
              - '.github/workflows/build.yml'
              - 'src/common/**'
              - 'src/portfolio-agent/**'
            videowall:
              - '.github/workflows/build.yml'
              - 'src/common/**'
              - 'src/videowall/**'
      - name: Filter Paths result
        shell: bash
        run: |
          echo "App changes detected at following apps: ${{ steps.filter.outputs.changes }}"

  build-app:
    # This joib will build the specific app(s). Will be called as matrix for all apps with changes detected.
    needs: filter-paths
    runs-on: ubuntu-latest
  
    strategy:
      matrix:
        app: ${{ fromJson(needs.filter-paths.outputs.changed_apps) }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: src/${{ matrix.app }}/package-lock.json
  
      - name: Install dependencies
        working-directory: src/${{ matrix.app }}
        run: npm ci

      - name: Build app
        working-directory: src/${{ matrix.app }}
        run: npm run build
      
      - name: Upload dist artifact
        uses: actions/upload-artifact@v7
        with:
          name: dist-${{ matrix.app }}
          path: ./${{ matrix.app }}
  
  push-apps:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Test 2
        shell: bash
        run: |
          echo "Do Git commit for: ${{ matrix.app }}"

      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Download all app dist artifacts
        uses: actions/download-artifact@v8
          
      - name: What has changes?
        shell: bash
        run: |
          echo "from JSON: ${{ fromJson(needs.filter-paths.outputs.changed_apps) }}"
          echo "original: ${{ needs.filter-paths.outputs.changed_apps }}"
          echo "joined: ${{ join(needs.filter-paths.outputs.changed_apps, ' ') }}"

      # - name: Commit build artifacts
      #   run: |
      #     git config user.name "github-actions" 
      #     git config user.email "github-actions@github.com" 
      #     git add videowall
      #     if git diff --cached --quiet; then
      #       echo "No changes to commit"
      #     else
      #       git commit -m "Videowall: update build artifacts"
      #       git push
      #     fi
